import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requireBusinessAccess } from "@/lib/auth/require-user";
import { calculateBusinessPeriodProfit, loadOrderTable } from "@/lib/profit-engine/server";
import { getProductProfitability, getMarketingProfitability, getShippingIntelligence, getRtoIntelligence } from "@/lib/analytics/server";
import { getForwardOrders, buildProfitInput, normalizeSettings } from "@/lib/profit-engine/server";
import { projectForwardOrders } from "@/lib/forecast-engine";

const schema=z.object({businessId:z.string().uuid(),start:z.string().date(),end:z.string().date(),type:z.enum(["profit","orders","products","marketing","shipping","rto","forecast"])});
function csv(rows:any[]){if(!rows.length)return "";const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))].filter(k=>typeof rows[0]?.[k]!=="object");const esc=(v:any)=>`"${String(v??"").replaceAll('"','""')}"`;return [keys.map(esc).join(","),...rows.map(r=>keys.map(k=>esc(r[k])).join(","))].join("\n");}
export async function GET(req:NextRequest){try{const q=schema.parse(Object.fromEntries(req.nextUrl.searchParams.entries()));await requireBusinessAccess(q.businessId);let rows:any[]=[];if(q.type==='orders'){const d=await loadOrderTable(q.businessId,q.start,q.end,0,1000);rows=d.rows.map((r:any)=>({orderNumber:r.order_number,date:r.order_date,customer:r.customer_name,paymentMethod:r.payment_method,orderValue:r.gross_sale,status:r.status,effectiveStatus:r.effective_status,cogs:r.economics.cogs,shipping:r.economics.shipping,checkoutFee:r.economics.checkoutFee,pgFee:r.economics.pgFee,contributionBeforeMarketing:r.economics.contributionBeforeMarketing}));}else if(q.type==='profit'){const d=await calculateBusinessPeriodProfit(q.businessId,q.start,q.end);rows=[d.result];}else if(q.type==='products'){rows=await getProductProfitability(q.businessId,q.start,q.end)}else if(q.type==='marketing'){rows=(await getMarketingProfitability(q.businessId,q.start,q.end)).rows}else if(q.type==='shipping'){rows=(await getShippingIntelligence(q.businessId,q.start,q.end)).rows}else if(q.type==='rto'){const d=await getRtoIntelligence(q.businessId,q.start,q.end);rows=[{rtoOrders:d.count,rtoValue:d.value,rtoRate:d.rate},...d.byState.map((x:any)=>({dimension:'state',value:x.label,count:x.count}))];}else if(q.type==='forecast'){const rollEnd=q.end,rollStartDate=new Date(`${rollEnd}T00:00:00Z`);rollStartDate.setUTCDate(rollStartDate.getUTCDate()-29);const rollStart=rollStartDate.toISOString().slice(0,10);const [actual,rolling30]=await Promise.all([calculateBusinessPeriodProfit(q.businessId,q.start,q.end),calculateBusinessPeriodProfit(q.businessId,rollStart,rollEnd)]);const forward=await getForwardOrders(q.businessId,undefined,undefined,{},normalizeSettings(actual.business.settings).forwardStatuses);const inputs=forward.map((row:any)=>buildProfitInput(row,[],new Map()));const projection=projectForwardOrders(actual.result,inputs,normalizeSettings(actual.business.settings),rolling30.result.deliveryRate);rows=[projection];}return new NextResponse(csv(rows),{status:200,headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="ecom-profit-os-${q.type}-${q.start}-${q.end}.csv"`}});}catch(e:any){return NextResponse.json({error:e?.message??"Export failed."},{status:400});}}
