import Decimal from "decimal.js";
import type { EngineSettings,FeeRule,OrderEconomics,PeriodProfit,ProfitOrderInput } from "./types";
export const CALCULATION_VERSION="1.0.0";
Decimal.set({precision:40,rounding:Decimal.ROUND_HALF_UP});
const D=(v:Decimal.Value=0)=>new Decimal(v??0);
const rtoStatus=(s:string)=>["RTO_PROCESSING","RTO_IN_TRANSIT","RTO_DELIVERED"].includes(s);
const shippedStatus=(s:string)=>["SHIPPED","IN_TRANSIT","REACHED_DESTINATION","DELIVERED","RTO_PROCESSING","RTO_IN_TRANSIT","RTO_DELIVERED","UNDELIVERED"].includes(s);
export function calculateFee(value:Decimal.Value,rule:FeeRule){let fee=D(rule.flatFee);if(rule.method==="percentage"||rule.method==="hybrid")fee=fee.plus(D(value).mul(D(rule.percentage)));if(rule.minimumFee!=null&&fee.lt(D(rule.minimumFee)))fee=D(rule.minimumFee);if("maximumFee"in rule&&rule.maximumFee!=null&&fee.gt(D(rule.maximumFee)))fee=D(rule.maximumFee);return fee;}
export function calculateOrderEconomics(order:ProfitOrderInput,settings:EngineSettings):OrderEconomics{const gross=D(order.grossSale),refund=D(order.refundedAmount),cancelled=order.status==="CANCELLED",rto=!cancelled&&rtoStatus(order.status),actual=order.status==="DELIVERED",effective=!cancelled&&!rto&&(actual||(settings.treatPrepaidAsEffectiveDelivered&&order.paymentMethod==="prepaid"));const delivered=effective?gross.minus(refund):D(0);const cogs=effective?order.lines.reduce((s,l)=>s.plus(D(l.quantity).mul(D(l.unitCost))),D(0)):D(0);const shipping=order.shipping?.applicable?(settings.shippingRule==="sum"?D(order.shipping.totalFreight).plus(D(order.shipping.unbilledCharges)):Decimal.max(D(order.shipping.totalFreight),D(order.shipping.unbilledCharges))):D(0);const checkout=order.checkoutFeeOverride!=null?D(order.checkoutFeeOverride):calculateFee(gross,settings.checkoutFee);const pg=order.pgFeeOverride!=null?D(order.pgFeeOverride):order.paymentMethod==="prepaid"?calculateFee(gross,settings.pgFee):D(0);const manual=(order.manualAdjustments??[]).reduce((s,a)=>s.plus(D(a.amount)),D(0));const contribution=delivered.minus(cogs).minus(shipping).minus(checkout).minus(pg).minus(manual);let effectiveStatus:"EFFECTIVE_DELIVERED"|"DELIVERED"|"RTO"|"OPEN"|"CANCELLED"="OPEN";if(cancelled)effectiveStatus="CANCELLED";else if(effective)effectiveStatus=actual?"DELIVERED":"EFFECTIVE_DELIVERED";else if(rto)effectiveStatus="RTO";return {orderId:order.orderId,orderNumber:order.orderNumber,grossSale:gross.toNumber(),deliveredRevenue:delivered.toNumber(),effectiveDelivered:effective,effectiveStatus,cogs:cogs.toNumber(),shipping:shipping.toNumber(),checkoutFee:checkout.toNumber(),pgFee:pg.toNumber(),contributionBeforeMarketing:contribution.toNumber(),refundAdjustment:refund.toNumber(),manualAdjustment:manual.toNumber()};}
export function calculatePeriodProfit(orders:ProfitOrderInput[],settings:EngineSettings,metaSpend:Decimal.Value=0):PeriodProfit{const economics=orders.map(o=>calculateOrderEconomics(o,settings));const sum=(f:(x:OrderEconomics)=>Decimal.Value)=>economics.reduce((a,x)=>a.plus(D(f(x))),D(0));const gross=sum(x=>x.grossSale),delivered=sum(x=>x.deliveredRevenue),cogs=sum(x=>x.cogs),shipping=sum(x=>x.shipping),checkout=sum(x=>x.checkoutFee),pg=sum(x=>x.pgFee);const netShipped=economics.reduce((a,x,i)=>a.plus(shippedStatus(orders[i].status)?x.grossSale:0),D(0));const meta=D(metaSpend),metaGst=meta.mul(D(settings.metaGstRate)),marketing=meta.plus(metaGst),profit=delivered.minus(cogs).minus(shipping).minus(checkout).minus(pg).minus(marketing);const shipped=orders.filter(o=>shippedStatus(o.status)).length,eff=economics.filter(x=>x.effectiveDelivered).length,effUnits=economics.reduce((a,x,i)=>x.effectiveDelivered?a.plus(orders[i].lines.reduce((sum,l)=>sum.plus(D(l.quantity)),D(0))):a,D(0)),rto=orders.filter(o=>rtoStatus(o.status)).length,open=orders.filter(o=>!rtoStatus(o.status)&&o.status!=="DELIVERED"&&o.status!=="CANCELLED").length,den=shipped||orders.length;return {grossSale:gross.toNumber(),netSaleShipped:netShipped.toNumber(),deliveredRevenue:delivered.toNumber(),netProfit:profit.toNumber(),orders:orders.length,shipped,effectiveDelivered:eff,effectiveDeliveredUnits:effUnits.toNumber(),rto,open,deliveryRate:den?eff/den:0,rtoRate:orders.length?rto/orders.length:0,cogs:cogs.toNumber(),shipping:shipping.toNumber(),checkout:checkout.toNumber(),pg:pg.toNumber(),metaSpend:meta.toNumber(),metaGst:metaGst.toNumber(),effectiveMarketingCost:marketing.toNumber(),roas:marketing.gt(0)?delivered.div(marketing).toNumber():0,profitMargin:delivered.gt(0)?profit.div(delivered).toNumber():0,aov:orders.length?gross.div(orders.length).toNumber():0,profitPerDeliveredOrder:eff?profit.div(eff).toNumber():0,marketingCostPerDeliveredOrder:eff?marketing.div(eff).toNumber():0,orderEconomics:economics};}
export function calculateProjectedProfit(actual:PeriodProfit,additional:{deliveredRevenue:Decimal.Value;cogs:Decimal.Value;shipping:Decimal.Value;checkout:Decimal.Value;pg:Decimal.Value;marketingCost:Decimal.Value}){const p=D(additional.deliveredRevenue).minus(D(additional.cogs)).minus(D(additional.shipping)).minus(D(additional.checkout)).minus(D(additional.pg)).minus(D(additional.marketingCost));return {actualProfit:actual.netProfit,projectedAdditionalProfit:p.toNumber(),projectedTotalProfit:D(actual.netProfit).plus(p).toNumber()};}
