create extension if not exists pgcrypto;

create type public.business_status as enum ('active','inactive');
create type public.membership_status as enum ('active','invited','disabled');
create type public.integration_status as enum ('connected','disconnected','syncing','failed','needs_reauthorization','not_configured');
create type public.order_status as enum ('PLACED','PROCESSING','SHIPPED','IN_TRANSIT','REACHED_DESTINATION','DELIVERED','RTO_PROCESSING','RTO_IN_TRANSIT','RTO_DELIVERED','UNDELIVERED','CANCELLED','OPEN');
create type public.payment_method as enum ('prepaid','cod','unknown');
create type public.rule_method as enum ('percentage','flat','hybrid');
create type public.sync_status as enum ('queued','running','completed','partial','failed');
create type public.import_status as enum ('uploaded','previewed','validating','completed','completed_with_errors','failed');

create table public.roles(name text primary key,description text not null default '');
insert into public.roles values
('super_admin','Platform owner with global access'),('admin','Business administrator'),('client','Business user'),('analyst','Read-only analyst') on conflict do nothing;

create table public.users(id uuid primary key references auth.users(id) on delete cascade,email text not null,name text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table public.businesses(
 id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,currency text not null default 'INR',timezone text not null default 'Asia/Kolkata',status public.business_status not null default 'active',
 settings jsonb not null default jsonb_build_object('treat_prepaid_as_effective_delivered',true,'checkout_fee',jsonb_build_object('method','percentage','percentage',0.02,'flat_fee',0,'minimum_fee',0,'maximum_fee',null),'pg_fee',jsonb_build_object('method','percentage','percentage',0.02,'flat_fee',0),'meta_gst_rate',0.18,'shipping_rule','max','forward_statuses',jsonb_build_array('IN_TRANSIT','REACHED_DESTINATION'),'target_profit',null),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.memberships(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,user_id uuid not null references public.users(id) on delete cascade,role text not null references public.roles(name),status public.membership_status not null default 'active',created_at timestamptz not null default now(),unique(business_id,user_id));

create table public.integrations(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,provider text not null,status public.integration_status not null default 'not_configured',connected_at timestamptz,last_sync_at timestamptz,error_message text,metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(business_id,provider));
create table public.integration_accounts(id uuid primary key default gen_random_uuid(),integration_id uuid not null references public.integrations(id) on delete cascade,account_name text,external_account_id text,credentials_encrypted text,refresh_token_encrypted text,scopes text[] not null default '{}',expires_at timestamptz,metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(integration_id,external_account_id));

create table public.products(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,external_product_id text,title text not null,product_type text,vendor text,handle text,status text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(business_id,external_product_id));
create table public.variants(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,product_id uuid not null references public.products(id) on delete cascade,external_variant_id text,sku text,title text,price numeric(20,6),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(business_id,external_variant_id));
create table public.product_costs(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,scope text not null check(scope in('variant','product','category','default')),variant_id uuid references public.variants(id) on delete cascade,product_id uuid references public.products(id) on delete cascade,category text,cost_per_unit numeric(20,6) not null check(cost_per_unit>=0),effective_from date not null,notes text,created_by uuid references public.users(id),created_at timestamptz not null default now(),check((scope='variant' and variant_id is not null and product_id is null and category is null)or(scope='product' and product_id is not null and variant_id is null and category is null)or(scope='category' and category is not null and variant_id is null and product_id is null)or(scope='default' and variant_id is null and product_id is null and category is null)));
create index product_costs_lookup_idx on public.product_costs(business_id,scope,effective_from desc);

create table public.orders(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,provider text not null default 'shopify',external_order_id text,order_number text not null,order_date timestamptz not null,updated_at_source timestamptz,customer_name text,customer_email text,shipping_state text,shipping_pincode text,shipping_city text,payment_method public.payment_method not null default 'unknown',gross_sale numeric(20,6) not null default 0 check(gross_sale>=0),discount_amount numeric(20,6) not null default 0,shipping_revenue numeric(20,6) not null default 0,tax_amount numeric(20,6) not null default 0,refunded_amount numeric(20,6) not null default 0,status public.order_status not null default 'OPEN',financial_status text,fulfillment_status text,cancelled_at timestamptz,delivered_at timestamptz,pickup_date timestamptz,tags text[] not null default '{}',source_payload jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(business_id,provider,external_order_id),unique(business_id,order_number));
create index orders_business_date_idx on public.orders(business_id,order_date desc);
create index orders_business_status_idx on public.orders(business_id,status);
create index orders_business_payment_idx on public.orders(business_id,payment_method);
create index orders_business_source_idx on public.orders(business_id,provider,external_order_id);
create index orders_pickup_idx on public.orders(business_id,pickup_date);

create table public.order_items(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,order_id uuid not null references public.orders(id) on delete cascade,external_line_item_id text,variant_id uuid references public.variants(id) on delete set null,product_id uuid references public.products(id) on delete set null,product_title text,sku text,quantity numeric(20,6) not null check(quantity>=0),unit_price numeric(20,6) not null default 0,discount_amount numeric(20,6) not null default 0,line_total numeric(20,6) not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(business_id,order_id,external_line_item_id));
create index order_items_business_order_idx on public.order_items(business_id,order_id);
create index order_items_product_idx on public.order_items(business_id,product_id);
create index order_items_variant_idx on public.order_items(business_id,variant_id);
create table public.order_refunds(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,order_id uuid not null references public.orders(id) on delete cascade,external_refund_id text,amount numeric(20,6) not null check(amount>=0),refunded_at timestamptz not null,reason text,source_payload jsonb not null default '{}',unique(business_id,external_refund_id));

create table public.shipping_orders(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,provider text not null,external_shipment_id text not null,external_order_id text,order_id uuid references public.orders(id) on delete set null,awb text,courier_name text,shipment_status text,normalized_status public.order_status not null default 'OPEN',pickup_date timestamptz,delivery_date timestamptz,rto_initiated_at timestamptz,rto_delivered_at timestamptz,forward_shipping_charge numeric(20,6) not null default 0,rto_charge numeric(20,6) not null default 0,cod_charge numeric(20,6) not null default 0,gst_charge numeric(20,6) not null default 0,total_freight numeric(20,6) not null default 0,unbilled_charges numeric(20,6) not null default 0,zone text,billed_weight numeric(20,6),source_payload jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(business_id,provider,external_shipment_id));
create index shipping_orders_business_status_idx on public.shipping_orders(business_id,normalized_status);
create index shipping_orders_business_awb_idx on public.shipping_orders(business_id,awb);
create index shipping_orders_order_idx on public.shipping_orders(business_id,order_id);
create table public.shipping_events(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,shipping_order_id uuid not null references public.shipping_orders(id) on delete cascade,external_event_id text,status text,normalized_status public.order_status,event_at timestamptz not null,location text,remarks text,source_payload jsonb not null default '{}',unique(business_id,shipping_order_id,external_event_id));

create table public.marketing_accounts(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,provider text not null,external_account_id text not null,account_name text,currency text,status text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(business_id,provider,external_account_id));
create table public.marketing_spend(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,provider text not null default 'meta',marketing_account_id uuid references public.marketing_accounts(id) on delete cascade,source_row_key text not null,date date not null,campaign_id text,campaign_name text,adset_id text,adset_name text,ad_id text,ad_name text,spend numeric(20,6) not null default 0 check(spend>=0),impressions bigint not null default 0,reach bigint not null default 0,clicks bigint not null default 0,ctr numeric(20,8),cpm numeric(20,8),cpc numeric(20,8),purchases numeric(20,6) not null default 0,conversion_value numeric(20,6) not null default 0,source_payload jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(business_id,provider,marketing_account_id,source_row_key));
create index marketing_spend_date_idx on public.marketing_spend(business_id,date desc);
create index marketing_spend_campaign_idx on public.marketing_spend(business_id,campaign_id,date);

create table public.checkout_transactions(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,provider text not null,external_transaction_id text not null,order_id uuid references public.orders(id) on delete set null,order_number text,transaction_date timestamptz not null,payment_method public.payment_method not null default 'unknown',payment_status text,transaction_value numeric(20,6) not null default 0,checkout_fee numeric(20,6),currency text,source_payload jsonb not null default '{}',unique(business_id,provider,external_transaction_id));
create table public.payment_transactions(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,provider text not null,external_transaction_id text not null,order_id uuid references public.orders(id) on delete set null,transaction_date timestamptz not null,payment_method public.payment_method not null default 'unknown',status text,amount numeric(20,6) not null default 0,fee numeric(20,6),gst_amount numeric(20,6),source_payload jsonb not null default '{}',unique(business_id,provider,external_transaction_id));
create table public.cost_rules(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,key text not null,method public.rule_method not null,percentage numeric(20,8) not null default 0,flat_fee numeric(20,6) not null default 0,minimum_fee numeric(20,6),maximum_fee numeric(20,6),effective_from date not null,config jsonb not null default '{}',created_by uuid references public.users(id),created_at timestamptz not null default now(),unique(business_id,key,effective_from));
create table public.manual_adjustments(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,order_id uuid references public.orders(id) on delete cascade,adjustment_type text not null check(adjustment_type in('COGS','CHECKOUT_FEE','PG_FEE','SHIPPING','OPERATIONAL_COST','REFUND','OTHER_COST')),amount numeric(20,6) not null,reason text not null,created_by uuid not null references public.users(id),created_at timestamptz not null default now());

create table public.daily_metrics(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,metric_date date not null,metrics jsonb not null default '{}',calculation_version text not null,generated_at timestamptz not null default now(),unique(business_id,metric_date));
create table public.weekly_metrics(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,metric_week date not null,metrics jsonb not null default '{}',calculation_version text not null,generated_at timestamptz not null default now(),unique(business_id,metric_week));
create table public.monthly_metrics(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,metric_month date not null,metrics jsonb not null default '{}',calculation_version text not null,generated_at timestamptz not null default now(),unique(business_id,metric_month));
create table public.profit_snapshots(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,start_date date not null,end_date date not null,granularity text not null default 'period',metrics jsonb not null default '{}',calculation_version text not null,rules_used jsonb not null default '{}',generated_at timestamptz not null default now(),unique(business_id,start_date,end_date,granularity,calculation_version));

create table public.sync_jobs(id uuid primary key default gen_random_uuid(),business_id uuid references public.businesses(id) on delete cascade,provider text not null,job_type text not null,status public.sync_status not null default 'queued',started_at timestamptz,finished_at timestamptz,records_processed bigint not null default 0,records_created bigint not null default 0,records_updated bigint not null default 0,errors jsonb not null default '[]',cursor text,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create index sync_jobs_business_created_idx on public.sync_jobs(business_id,created_at desc);
create table public.sync_logs(id uuid primary key default gen_random_uuid(),sync_job_id uuid not null references public.sync_jobs(id) on delete cascade,level text not null check(level in('info','warn','error')),message text not null,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table public.audit_logs(id uuid primary key default gen_random_uuid(),business_id uuid references public.businesses(id) on delete cascade,user_id uuid references public.users(id) on delete set null,action text not null,entity_type text,entity_id uuid,old_value jsonb,new_value jsonb,ip_address inet,user_agent text,created_at timestamptz not null default now());
create index audit_logs_business_created_idx on public.audit_logs(business_id,created_at desc);
create table public.webhook_events(id uuid primary key default gen_random_uuid(),business_id uuid references public.businesses(id) on delete cascade,provider text not null,external_event_id text not null,topic text,signature text,payload jsonb not null,status text not null default 'received',error_message text,received_at timestamptz not null default now(),processed_at timestamptz,unique(provider,external_event_id));
create table public.csv_imports(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,provider text not null,storage_path text,file_name text not null,status public.import_status not null default 'uploaded',rows_detected bigint not null default 0,rows_imported bigint not null default 0,rows_skipped bigint not null default 0,rows_duplicated bigint not null default 0,rows_invalid bigint not null default 0,rows_updated bigint not null default 0,validation_errors jsonb not null default '[]',column_mapping jsonb not null default '{}',created_by uuid references public.users(id),created_at timestamptz not null default now(),completed_at timestamptz);
create table public.calculation_versions(version text primary key,description text not null,rules jsonb not null default '{}',released_at timestamptz not null default now());
insert into public.calculation_versions values('1.0.0','Initial centralized profitability engine','{"shipping_rule":"max","meta_gst_rate":0.18,"checkout_fee_rate":0.02,"prepaid_pg_fee_rate":0.02,"prepaid_effective_delivered":true}',now()) on conflict do nothing;
create table public.notifications(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,user_id uuid references public.users(id) on delete cascade,title text not null,message text not null,severity text not null default 'info',read_at timestamptz,created_at timestamptz not null default now());

create or replace function public.set_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now(); return new; end$$;

do $$declare t text;begin foreach t in array array['users','businesses','integrations','integration_accounts','products','variants','orders','order_items','shipping_orders','marketing_accounts','marketing_spend'] loop execute format('create trigger %I_updated_at before update on public.%I for each row execute function public.set_updated_at()',t,t); end loop;end$$;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.users(id,email,name) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'name','')) on conflict(id) do update set email=excluded.email; return new;end$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.is_super_admin() returns boolean language sql stable security definer set search_path=public,auth as $$select exists(select 1 from public.memberships m where m.user_id=auth.uid() and m.role='super_admin' and m.status='active')$$;
create or replace function public.user_can_access_business(target_business_id uuid) returns boolean language sql stable security definer set search_path=public,auth as $$select public.is_super_admin() or exists(select 1 from public.memberships m where m.business_id=target_business_id and m.user_id=auth.uid() and m.status='active')$$;
create or replace function public.user_can_write_business(target_business_id uuid) returns boolean language sql stable security definer set search_path=public,auth as $$select exists(select 1 from public.memberships m where m.business_id=target_business_id and m.user_id=auth.uid() and m.status='active' and m.role in('super_admin','admin','client'))$$;

alter table public.users enable row level security;
alter table public.businesses enable row level security;
alter table public.memberships enable row level security;
alter table public.roles enable row level security;

do $$declare t text;begin foreach t in array array['integrations','integration_accounts','products','variants','product_costs','orders','order_items','order_refunds','shipping_orders','shipping_events','marketing_accounts','marketing_spend','checkout_transactions','payment_transactions','cost_rules','manual_adjustments','daily_metrics','weekly_metrics','monthly_metrics','profit_snapshots','sync_jobs','sync_logs','audit_logs','webhook_events','csv_imports','notifications'] loop execute format('alter table public.%I enable row level security',t); end loop;end$$;
alter table public.calculation_versions enable row level security;

create policy users_select on public.users for select using(id=auth.uid());
create policy users_update on public.users for update using(id=auth.uid()) with check(id=auth.uid());
create policy roles_select on public.roles for select using(true);
create policy businesses_select on public.businesses for select using(public.user_can_access_business(id));
create policy businesses_insert on public.businesses for insert with check(public.is_super_admin());
create policy businesses_update on public.businesses for update using(public.user_can_access_business(id) and(public.is_super_admin() or exists(select 1 from public.memberships m where m.business_id=id and m.user_id=auth.uid() and m.role in('admin','super_admin') and m.status='active'))) with check(public.user_can_access_business(id));
create policy memberships_select on public.memberships for select using(user_id=auth.uid() or public.is_super_admin() or public.user_can_access_business(business_id));
create policy memberships_write on public.memberships for all using(public.is_super_admin() or exists(select 1 from public.memberships m2 where m2.business_id=business_id and m2.user_id=auth.uid() and m2.role in('admin','super_admin') and m2.status='active')) with check(public.is_super_admin() or exists(select 1 from public.memberships m2 where m2.business_id=business_id and m2.user_id=auth.uid() and m2.role in('admin','super_admin') and m2.status='active'));

create policy integrations_select on public.integrations for select using(public.user_can_access_business(business_id));
create policy integrations_write on public.integrations for all using(public.user_can_write_business(business_id)) with check(public.user_can_write_business(business_id));
create policy integration_accounts_select on public.integration_accounts for select using(exists(select 1 from public.integrations i where i.id=integration_id and public.user_can_access_business(i.business_id)));
create policy integration_accounts_write on public.integration_accounts for all using(exists(select 1 from public.integrations i where i.id=integration_id and public.user_can_write_business(i.business_id))) with check(exists(select 1 from public.integrations i where i.id=integration_id and public.user_can_write_business(i.business_id)));

do $$declare t text;begin foreach t in array array['products','variants','product_costs','orders','order_items','order_refunds','shipping_orders','shipping_events','marketing_accounts','marketing_spend','checkout_transactions','payment_transactions','cost_rules','manual_adjustments','daily_metrics','weekly_metrics','monthly_metrics','profit_snapshots','csv_imports','notifications'] loop execute format('create policy %I_select on public.%I for select using(public.user_can_access_business(business_id))',t,t); execute format('create policy %I_insert on public.%I for insert with check(public.user_can_write_business(business_id))',t,t); execute format('create policy %I_update on public.%I for update using(public.user_can_write_business(business_id)) with check(public.user_can_write_business(business_id))',t,t); execute format('create policy %I_delete on public.%I for delete using(public.user_can_write_business(business_id))',t,t); end loop;end$$;
create policy sync_jobs_select on public.sync_jobs for select using(business_id is null or public.user_can_access_business(business_id));
create policy sync_logs_select on public.sync_logs for select using(exists(select 1 from public.sync_jobs j where j.id=sync_job_id and(j.business_id is null or public.user_can_access_business(j.business_id))));
create policy audit_logs_select on public.audit_logs for select using(business_id is null or public.user_can_access_business(business_id));
create policy audit_logs_insert on public.audit_logs for insert with check(business_id is null or public.user_can_write_business(business_id));
create policy webhook_events_select on public.webhook_events for select using(business_id is null or public.user_can_access_business(business_id));
create policy calculation_versions_select on public.calculation_versions for select using(true);

insert into storage.buckets(id,name,public) values('csv-imports','csv-imports',false) on conflict(id) do nothing;
create policy csv_storage_select on storage.objects for select to authenticated using(bucket_id='csv-imports' and public.user_can_access_business((storage.foldername(name))[1]::uuid));
create policy csv_storage_insert on storage.objects for insert to authenticated with check(bucket_id='csv-imports' and public.user_can_write_business((storage.foldername(name))[1]::uuid));
create policy csv_storage_delete on storage.objects for delete to authenticated using(bucket_id='csv-imports' and public.user_can_write_business((storage.foldername(name))[1]::uuid));

create or replace function public.create_business_for_current_user(p_name text,p_slug text,p_currency text default 'INR',p_timezone text default 'Asia/Kolkata') returns uuid language plpgsql security definer set search_path=public,auth as $$declare new_business_id uuid;begin if auth.uid() is null then raise exception 'not_authenticated';end if;insert into public.businesses(name,slug,currency,timezone) values(trim(p_name),lower(trim(p_slug)),upper(trim(p_currency)),trim(p_timezone)) returning id into new_business_id;insert into public.memberships(business_id,user_id,role,status) values(new_business_id,auth.uid(),'client','active');insert into public.audit_logs(business_id,user_id,action,entity_type,new_value) values(new_business_id,auth.uid(),'business.created','business',jsonb_build_object('name',p_name,'slug',p_slug));return new_business_id;end$$;
grant execute on function public.create_business_for_current_user(text,text,text,text) to authenticated;
