"use client";
import { useState } from "react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";

export function ManualCheckoutForm({businessId}:{businessId:string}) {
  const [tx,setTx]=useState(""),[order,setOrder]=useState(""),[date,setDate]=useState(new Date().toISOString()),[method,setMethod]=useState<"prepaid"|"cod"|"unknown">("prepaid"),[value,setValue]=useState(""),[fee,setFee]=useState(""),[msg,setMsg]=useState("");
  async function save(){const r=await fetch("/api/checkout/manual",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({businessId,externalTransactionId:tx,orderNumber:order||undefined,transactionDate:date,paymentMethod:method,transactionValue:value,checkoutFee:fee||undefined,currency:"INR"})});const j=await r.json();setMsg(r.ok?"Checkout transaction saved and audited.":j.error??"Could not save transaction.");if(r.ok){setTx("");setValue("");setFee("")}}
  return <div className="rounded-lg border bg-white p-5"><div className="text-sm font-semibold">Manual checkout transaction</div><p className="mt-1 text-xs text-slate-500">Use this only when a checkout API is not configured. Data remains durable in PostgreSQL and is audited.</p><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-6"><div><Label>Transaction ID</Label><Input value={tx} onChange={e=>setTx(e.target.value)} required/></div><div><Label>Order #</Label><Input value={order} onChange={e=>setOrder(e.target.value)} placeholder="Optional"/></div><div><Label>Date</Label><Input type="datetime-local" value={date.slice(0,16)} onChange={e=>setDate(new Date(e.target.value).toISOString())} required/></div><div><Label>Payment</Label><select className="h-9 w-full rounded-md border px-3 text-sm" value={method} onChange={e=>setMethod(e.target.value as any)}><option value="prepaid">Prepaid</option><option value="cod">COD</option><option value="unknown">Unknown</option></select></div><div><Label>Transaction Value</Label><Input type="number" min="0" step="0.000001" value={value} onChange={e=>setValue(e.target.value)} required/></div><div><Label>Checkout Fee</Label><Input type="number" min="0" step="0.000001" value={fee} onChange={e=>setFee(e.target.value)} placeholder="Optional"/></div></div><div className="mt-4 flex items-center gap-3"><Button onClick={save} disabled={!tx||!value}>Save transaction</Button>{msg&&<span className="text-xs text-slate-500">{msg}</span>}</div></div>;
}
